Green Belt [WIP]
AppSecure-nrw/security-belts pull request #48
Opened 2021-03-16 12:28 UTC by mvollmary

2021-03-22 14:16 UTC, StefanDziwok approved these changes

2021-03-24 09:44 UTC, merschs requested changes
I think we should finish green/environment-dependent-configuration-parameters.md before merging. Currently, the assessment is still work in progress.

2021-03-24 09:45 UTC, mvollmary commented
This PR is still in progress. I only created it so we have this topic in our project board. I converted it to a draft (didn't know about this feature :tada:)

2021-04-22 13:44 UTC, merschs commented on green/ensure-only-using-components-which-are-under-active-development.md
> +- Modern technologies help to minimize your attack surface.
what does modern mean? Is here "up-to-date" meant?

2021-04-22 13:48 UTC, merschs commented on green/environment-dependent-configuration-parameters.md
> +- [Same Artifact for Environments](../orange/same-artifact-for-environments.md)
I think I would like it to mark activities which are not of this belt, e.g., "Orange Belt: Same Artificat ..."

2021-04-22 13:50 UTC, merschs commented on green/integration-of-vulnerability-issues-into-the-development-process.md
> +# Integration of vulnerability issues into the development process
```suggestion
# Integration of Vulnerability Issues into the Development Process
```

2021-04-22 13:50 UTC, merschs commented on green/integration-of-vulnerability-issues-into-the-development-process.md
> +- [Treatment of vulnerabilities with severity high or higher](treatment-of-vulnerabilities-with-severity-high-or-higher.md)
```suggestion
- [Treatment of Vulnerabilities with Severity High or Higher](treatment-of-vulnerabilities-with-severity-high-or-higher.md)
```

2021-04-22 13:51 UTC, merschs commented on green/environment-dependent-configuration-parameters.md
> +# Environment-dependent configuration parameters
```suggestion
# Environment-Dependent Configuration Parameters
```

2021-04-22 13:53 UTC, merschs commented on green/ensure-only-using-components-which-are-under-active-development.md
> +# Ensure only using components which are under active development
```suggestion
# Ensure Only Using Components Which Are Under Active Development
```

2021-04-22 13:54 UTC, merschs commented on green/README.md
> +- [Ensure only using components which are under active development](ensure-only-using-components-which-are-under-active-development.md)
```suggestion
- [Ensure Only Using Components Which Are Under Active Development](ensure-only-using-components-which-are-under-active-development.md)
```

2021-04-22 13:55 UTC, merschs commented on green/README.md
> +- [Environment-dependent configuration parameters](environment-dependent-configuration-parameters.md)
```suggestion
- [Environment-Dependent Configuration Parameters](environment-dependent-configuration-parameters.md)
```

2021-04-22 13:58 UTC, merschs commented on green/static-analysis-for-all-self-written-components.md
> +# Static analysis for all self-written components
```suggestion
# Static Analysis for All Self-Written Components
```

2021-04-22 13:58 UTC, merschs commented on green/README.md
> +- [Static analysis for all self-written components](static-analysis-for-all-self-written-components.md)
```suggestion
- [Static Analysis for All Self-Written Components](static-analysis-for-all-self-written-components.md)
```

2021-04-22 14:01 UTC, merschs commented on green/test-security-configuration-of-cloud-environments.md
> +# Test security configuration of cloud environments
```suggestion
# Test Security Configuration of Cloud Environments
```

2021-04-22 14:02 UTC, merschs commented on green/README.md
> +- [Test security configuration of cloud environments](test-security-configuration-of-cloud-environments.md)
```suggestion
- [Test Security Configuration of Cloud Environments](test-security-configuration-of-cloud-environments.md)
```

2021-04-22 14:03 UTC, merschs commented on green/test-security-configuration-of-infrastructure.md
> +# Test security configuration of infrastructure
```suggestion
# Test Security Configuration of Infrastructure
```

2021-04-22 14:03 UTC, merschs commented on green/README.md
> +- [Test security configuration of infrastructure](test-security-configuration-of-infrastructure.md)
```suggestion
- [Test Security Configuration of Infrastructure](test-security-configuration-of-infrastructure.md)
```

2021-04-22 14:05 UTC, merschs commented on green/treatment-of-vulnerabilities-with-severity-high-or-higher.md
> +# Treatment of vulnerabilities with severity high or higher
```suggestion
# Treatment of Vulnerabilities With Severity High or Higher
```

2021-04-22 14:05 UTC, merschs commented on green/README.md
> +- [Treatment of vulnerabilities with severity high or higher](treatment-of-vulnerabilities-with-severity-high-or-higher.md)
```suggestion
- [Treatment of Vulnerabilities With Severity High or Higher](treatment-of-vulnerabilities-with-severity-high-or-higher.md)
```

2021-04-22 14:08 UTC, merschs commented on green/treatment-of-vulnerabilities-with-severity-high-or-higher.md
> +- The software is free of high-impact vulnerabilities, which decreases the chance of denial of service attacks and lost or manipulation of confidential data.
```suggestion
- The software is free of high-impact vulnerabilities, which decreases the chance of successful denial of service attacks and loss or manipulation of confidential data.
```

2021-04-22 14:09 UTC, merschs commented on green/treatment-of-vulnerabilities-with-severity-high-or-higher.md
> +- Show the fix for the latest *n* high criticality findings.
```suggestion
- Show the fix for the latest *n* high severity findings.
```

2021-04-22 14:10 UTC, merschs commented on green/treatment-of-vulnerabilities-with-severity-high-or-higher.md
> +- [Static analysis for all self-written components](static-analysis-for-all-self-written-components.md)
```suggestion
- [Static Analysis for All Self-Written Components](static-analysis-for-all-self-written-components.md)
```

2021-04-22 14:12 UTC, merschs commented on green/README.md
> +- [Integration of vulnerability issues into the development process](integration-of-vulnerability-issues-into-the-development-process.md)
```suggestion
- [Integration of Vulnerability Issues into the Development Process](integration-of-vulnerability-issues-into-the-development-process.md)
```

2021-04-22 14:14 UTC, merschs submitted a review, later dismissed
some minor remarks and wording regarding high severity fixes
+ headling capitalization

2021-04-28 13:03 UTC, TimSro approved these changes

2021-04-29 11:56 UTC, merged